### ISSUE TITLE
Evaluation results

### ISSUE THREAD

**Issue by TinoRed** [nbishdev/templates_to_language_evaluation#1]
Hi @nbishdev ! Thank you for your work, it was very interesting!

Could you share the raw results obtained from the single models you evaluated?

Which model performed better on the task of generating text? - in terms of BLEU score or any other metric you used to evaluate the goodness of the results.

Thank you in advance, this kind of research really helps the community!

**Comment by nepiskopos** [comment]
Hi @TinoRed ! Thank you for your interest in our research!

In our [report](https://github.com/nbishdev/templates_to_language_evaluation/blob/main/D.%20Roussis%2C%20N.%20Episkopos%20-%20DBS%20Project%20Report.pdf) we have included our results and observations, so you should be able to find the answer there.
